//go:build !ignore_autogenerated

/*
Copyright 2024 Bud Studio.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudAIScaler) DeepCopyInto(out *BudAIScaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudAIScaler.
func (in *BudAIScaler) DeepCopy() *BudAIScaler {
	if in == nil {
		return nil
	}
	out := new(BudAIScaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BudAIScaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudAIScalerList) DeepCopyInto(out *BudAIScalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BudAIScaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudAIScalerList.
func (in *BudAIScalerList) DeepCopy() *BudAIScalerList {
	if in == nil {
		return nil
	}
	out := new(BudAIScalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BudAIScalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudAIScalerSpec) DeepCopyInto(out *BudAIScalerSpec) {
	*out = *in
	out.ScaleTargetRef = in.ScaleTargetRef
	if in.SubTargetSelector != nil {
		in, out := &in.SubTargetSelector, &out.SubTargetSelector
		*out = new(SubTargetSelector)
		**out = **in
	}
	if in.MinReplicas != nil {
		in, out := &in.MinReplicas, &out.MinReplicas
		*out = new(int32)
		**out = **in
	}
	if in.MetricsSources != nil {
		in, out := &in.MetricsSources, &out.MetricsSources
		*out = make([]MetricSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GPUConfig != nil {
		in, out := &in.GPUConfig, &out.GPUConfig
		*out = new(GPUScalingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.CostConfig != nil {
		in, out := &in.CostConfig, &out.CostConfig
		*out = new(CostConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PredictionConfig != nil {
		in, out := &in.PredictionConfig, &out.PredictionConfig
		*out = new(PredictionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ScheduleHints != nil {
		in, out := &in.ScheduleHints, &out.ScheduleHints
		*out = make([]ScheduleHint, len(*in))
		copy(*out, *in)
	}
	if in.MultiClusterConfig != nil {
		in, out := &in.MultiClusterConfig, &out.MultiClusterConfig
		*out = new(MultiClusterConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Behavior != nil {
		in, out := &in.Behavior, &out.Behavior
		*out = new(ScalingBehavior)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudAIScalerSpec.
func (in *BudAIScalerSpec) DeepCopy() *BudAIScalerSpec {
	if in == nil {
		return nil
	}
	out := new(BudAIScalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BudAIScalerStatus) DeepCopyInto(out *BudAIScalerStatus) {
	*out = *in
	if in.LastScaleTime != nil {
		in, out := &in.LastScaleTime, &out.LastScaleTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScalingHistory != nil {
		in, out := &in.ScalingHistory, &out.ScalingHistory
		*out = make([]ScalingDecision, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GPUStatus != nil {
		in, out := &in.GPUStatus, &out.GPUStatus
		*out = new(GPUStatus)
		**out = **in
	}
	if in.CostStatus != nil {
		in, out := &in.CostStatus, &out.CostStatus
		*out = new(CostStatus)
		**out = **in
	}
	if in.PredictionStatus != nil {
		in, out := &in.PredictionStatus, &out.PredictionStatus
		*out = new(PredictionStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.LearningStatus != nil {
		in, out := &in.LearningStatus, &out.LearningStatus
		*out = new(LearningStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.MultiClusterStatus != nil {
		in, out := &in.MultiClusterStatus, &out.MultiClusterStatus
		*out = new(MultiClusterStatus)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BudAIScalerStatus.
func (in *BudAIScalerStatus) DeepCopy() *BudAIScalerStatus {
	if in == nil {
		return nil
	}
	out := new(BudAIScalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostConfig) DeepCopyInto(out *CostConfig) {
	*out = *in
	if in.BudgetPerHour != nil {
		in, out := &in.BudgetPerHour, &out.BudgetPerHour
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.BudgetPerDay != nil {
		in, out := &in.BudgetPerDay, &out.BudgetPerDay
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostConfig.
func (in *CostConfig) DeepCopy() *CostConfig {
	if in == nil {
		return nil
	}
	out := new(CostConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CostStatus) DeepCopyInto(out *CostStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CostStatus.
func (in *CostStatus) DeepCopy() *CostStatus {
	if in == nil {
		return nil
	}
	out := new(CostStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUScalingConfig) DeepCopyInto(out *GPUScalingConfig) {
	*out = *in
	if in.GPUMemoryThreshold != nil {
		in, out := &in.GPUMemoryThreshold, &out.GPUMemoryThreshold
		*out = new(int32)
		**out = **in
	}
	if in.GPUComputeThreshold != nil {
		in, out := &in.GPUComputeThreshold, &out.GPUComputeThreshold
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUScalingConfig.
func (in *GPUScalingConfig) DeepCopy() *GPUScalingConfig {
	if in == nil {
		return nil
	}
	out := new(GPUScalingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GPUStatus) DeepCopyInto(out *GPUStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GPUStatus.
func (in *GPUStatus) DeepCopy() *GPUStatus {
	if in == nil {
		return nil
	}
	out := new(GPUStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceEngineConfig) DeepCopyInto(out *InferenceEngineConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceEngineConfig.
func (in *InferenceEngineConfig) DeepCopy() *InferenceEngineConfig {
	if in == nil {
		return nil
	}
	out := new(InferenceEngineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LearningStatus) DeepCopyInto(out *LearningStatus) {
	*out = *in
	if in.OldestDataPoint != nil {
		in, out := &in.OldestDataPoint, &out.OldestDataPoint
		*out = (*in).DeepCopy()
	}
	if in.LastCalibration != nil {
		in, out := &in.LastCalibration, &out.LastCalibration
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LearningStatus.
func (in *LearningStatus) DeepCopy() *LearningStatus {
	if in == nil {
		return nil
	}
	out := new(LearningStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSource) DeepCopyInto(out *MetricSource) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.InferenceEngineConfig != nil {
		in, out := &in.InferenceEngineConfig, &out.InferenceEngineConfig
		*out = new(InferenceEngineConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSource.
func (in *MetricSource) DeepCopy() *MetricSource {
	if in == nil {
		return nil
	}
	out := new(MetricSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterConfig) DeepCopyInto(out *MultiClusterConfig) {
	*out = *in
	if in.TargetClusters != nil {
		in, out := &in.TargetClusters, &out.TargetClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ClusterWeights != nil {
		in, out := &in.ClusterWeights, &out.ClusterWeights
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterConfig.
func (in *MultiClusterConfig) DeepCopy() *MultiClusterConfig {
	if in == nil {
		return nil
	}
	out := new(MultiClusterConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterStatus) DeepCopyInto(out *MultiClusterStatus) {
	*out = *in
	if in.ClusterDistribution != nil {
		in, out := &in.ClusterDistribution, &out.ClusterDistribution
		*out = make(map[string]int32, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.HealthyClusters != nil {
		in, out := &in.HealthyClusters, &out.HealthyClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UnhealthyClusters != nil {
		in, out := &in.UnhealthyClusters, &out.UnhealthyClusters
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterStatus.
func (in *MultiClusterStatus) DeepCopy() *MultiClusterStatus {
	if in == nil {
		return nil
	}
	out := new(MultiClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionConfig) DeepCopyInto(out *PredictionConfig) {
	*out = *in
	if in.LookAheadMinutes != nil {
		in, out := &in.LookAheadMinutes, &out.LookAheadMinutes
		*out = new(int32)
		**out = **in
	}
	if in.HistoricalDataDays != nil {
		in, out := &in.HistoricalDataDays, &out.HistoricalDataDays
		*out = new(int32)
		**out = **in
	}
	if in.PredictionMetrics != nil {
		in, out := &in.PredictionMetrics, &out.PredictionMetrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SeasonalMetrics != nil {
		in, out := &in.SeasonalMetrics, &out.SeasonalMetrics
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionConfig.
func (in *PredictionConfig) DeepCopy() *PredictionConfig {
	if in == nil {
		return nil
	}
	out := new(PredictionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PredictionStatus) DeepCopyInto(out *PredictionStatus) {
	*out = *in
	if in.NextPredictedChange != nil {
		in, out := &in.NextPredictedChange, &out.NextPredictedChange
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PredictionStatus.
func (in *PredictionStatus) DeepCopy() *PredictionStatus {
	if in == nil {
		return nil
	}
	out := new(PredictionStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingBehavior) DeepCopyInto(out *ScalingBehavior) {
	*out = *in
	if in.ScaleUp != nil {
		in, out := &in.ScaleUp, &out.ScaleUp
		*out = new(ScalingRules)
		(*in).DeepCopyInto(*out)
	}
	if in.ScaleDown != nil {
		in, out := &in.ScaleDown, &out.ScaleDown
		*out = new(ScalingRules)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingBehavior.
func (in *ScalingBehavior) DeepCopy() *ScalingBehavior {
	if in == nil {
		return nil
	}
	out := new(ScalingBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingDecision) DeepCopyInto(out *ScalingDecision) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingDecision.
func (in *ScalingDecision) DeepCopy() *ScalingDecision {
	if in == nil {
		return nil
	}
	out := new(ScalingDecision)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingPolicy) DeepCopyInto(out *ScalingPolicy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingPolicy.
func (in *ScalingPolicy) DeepCopy() *ScalingPolicy {
	if in == nil {
		return nil
	}
	out := new(ScalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScalingRules) DeepCopyInto(out *ScalingRules) {
	*out = *in
	if in.StabilizationWindowSeconds != nil {
		in, out := &in.StabilizationWindowSeconds, &out.StabilizationWindowSeconds
		*out = new(int32)
		**out = **in
	}
	if in.SelectPolicy != nil {
		in, out := &in.SelectPolicy, &out.SelectPolicy
		*out = new(ScalingPolicySelect)
		**out = **in
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make([]ScalingPolicy, len(*in))
		copy(*out, *in)
	}
	if in.MaxScaleRate != nil {
		in, out := &in.MaxScaleRate, &out.MaxScaleRate
		*out = new(string)
		**out = **in
	}
	if in.Tolerance != nil {
		in, out := &in.Tolerance, &out.Tolerance
		*out = new(string)
		**out = **in
	}
	if in.StartingPods != nil {
		in, out := &in.StartingPods, &out.StartingPods
		*out = new(StartingPodsConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScalingRules.
func (in *ScalingRules) DeepCopy() *ScalingRules {
	if in == nil {
		return nil
	}
	out := new(ScalingRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScheduleHint) DeepCopyInto(out *ScheduleHint) {
	*out = *in
	out.Duration = in.Duration
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScheduleHint.
func (in *ScheduleHint) DeepCopy() *ScheduleHint {
	if in == nil {
		return nil
	}
	out := new(ScheduleHint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartingPodsConfig) DeepCopyInto(out *StartingPodsConfig) {
	*out = *in
	if in.StartingPodWeight != nil {
		in, out := &in.StartingPodWeight, &out.StartingPodWeight
		*out = new(string)
		**out = **in
	}
	if in.MaxStartingPods != nil {
		in, out := &in.MaxStartingPods, &out.MaxStartingPods
		*out = new(int32)
		**out = **in
	}
	if in.MaxStartingPodPercent != nil {
		in, out := &in.MaxStartingPodPercent, &out.MaxStartingPodPercent
		*out = new(int32)
		**out = **in
	}
	if in.BypassGateOnPanic != nil {
		in, out := &in.BypassGateOnPanic, &out.BypassGateOnPanic
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartingPodsConfig.
func (in *StartingPodsConfig) DeepCopy() *StartingPodsConfig {
	if in == nil {
		return nil
	}
	out := new(StartingPodsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubTargetSelector) DeepCopyInto(out *SubTargetSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubTargetSelector.
func (in *SubTargetSelector) DeepCopy() *SubTargetSelector {
	if in == nil {
		return nil
	}
	out := new(SubTargetSelector)
	in.DeepCopyInto(out)
	return out
}
